[theme]
primaryColor = "#64ffda"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
